---
pull_request_rules:
  -
    actions:
      comment:
        message: "Automatic squash & merge 🚀"
      merge:
        method: squash
    conditions:
      - author!=Clivern
      - approved-reviews-by=Clivern
      - label=merge
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
    name: "Automatic Merge 🚀"
  -
    actions:
      comment:
        message: "Automatic merge 🚀"
      merge:
        method: merge
    conditions:
      - author=Clivern
      - label=merge
    name: "Automatic Merge 🚀"
  -
    actions:
      comment:
        message: "This pull request is now in conflicts. Could you please fix it? 🙏"
    conditions:
      - conflicts
    name: "Ask to Resolve Conflict"
  -
    actions:
      comment:
        message: "Automatic squash & merge 🚀"
      merge:
        method: squash
    conditions:
      - "author=renovate[bot]"
      - label=merge
      - status-success=continuous-integration/travis-ci/pr
      - status-success=continuous-integration/travis-ci/push
    name: "Automatic Merge for Renovate PRs 🚀"
